<?php

namespace App\Filament\Resources\Payrolls\Schemas;

use App\Enums\PayPeriodType;
use App\Enums\PayrollStatus;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class PayrollForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Payroll Details')
                    ->schema([
                        TextInput::make('payroll_number')
                            ->label('Payroll Number')
                            ->disabled()
                            ->dehydrated()
                            ->default(fn () => \App\Models\Payroll::generatePayrollNumber()),

                        Select::make('pay_period_type')
                            ->label('Pay Period Type')
                            ->options(
                                collect(PayPeriodType::cases())
                                    ->mapWithKeys(fn ($p) => [$p->value => $p->getLabel()])
                            )
                            ->required(),

                        DatePicker::make('pay_period_start')
                            ->label('Period Start')
                            ->required(),

                        DatePicker::make('pay_period_end')
                            ->label('Period End')
                            ->required()
                            ->afterOrEqual('pay_period_start'),
                    ])
                    ->columns(2),

                Section::make('Notes')
                    ->schema([
                        Textarea::make('notes')
                            ->label('Notes')
                            ->rows(3)
                            ->columnSpanFull(),
                    ]),

                Section::make('Summary')
                    ->schema([
                        Placeholder::make('status_display')
                            ->label('Status')
                            ->content(fn ($record) => $record?->status?->getLabel() ?? 'Draft'),

                        Placeholder::make('total_gross_display')
                            ->label('Total Gross')
                            ->content(fn ($record) => $record ? '₱' . number_format((float) $record->total_gross, 2) : '-'),

                        Placeholder::make('total_deductions_display')
                            ->label('Total Deductions')
                            ->content(fn ($record) => $record ? '₱' . number_format((float) $record->total_deductions, 2) : '-'),

                        Placeholder::make('total_net_display')
                            ->label('Total Net Pay')
                            ->content(fn ($record) => $record ? '₱' . number_format((float) $record->total_net, 2) : '-'),

                        Placeholder::make('generated_by_display')
                            ->label('Generated By')
                            ->content(fn ($record) => $record?->generatedBy?->name ?? '-'),

                        Placeholder::make('approved_by_display')
                            ->label('Approved By')
                            ->content(fn ($record) => $record?->approvedBy?->name ?? '-'),
                    ])
                    ->columns(3)
                    ->hidden(fn ($record) => ! $record),
            ]);
    }
}
