<?php

namespace App\Filament\Resources\Payrolls\Tables;

use App\Enums\PayPeriodType;
use App\Enums\PayrollStatus;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;

class PayrollsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('payroll_number')
                    ->label('Payroll #')
                    ->searchable()
                    ->sortable(),

                TextColumn::make('pay_period_start')
                    ->label('Period Start')
                    ->date('M d, Y')
                    ->sortable(),

                TextColumn::make('pay_period_end')
                    ->label('Period End')
                    ->date('M d, Y')
                    ->sortable(),

                TextColumn::make('pay_period_type')
                    ->label('Type')
                    ->badge()
                    ->color(fn (PayPeriodType $state): string => $state->getColor())
                    ->formatStateUsing(fn (PayPeriodType $state): string => $state->getLabel()),

                TextColumn::make('total_gross')
                    ->label('Gross')
                    ->money('PHP')
                    ->sortable(),

                TextColumn::make('total_deductions')
                    ->label('Deductions')
                    ->money('PHP')
                    ->sortable(),

                TextColumn::make('total_net')
                    ->label('Net Pay')
                    ->money('PHP')
                    ->sortable(),

                TextColumn::make('status')
                    ->label('Status')
                    ->badge()
                    ->color(fn (PayrollStatus $state): string => $state->getColor())
                    ->formatStateUsing(fn (PayrollStatus $state): string => $state->getLabel())
                    ->sortable(),

                TextColumn::make('generatedBy.name')
                    ->label('Generated By')
                    ->toggleable(),

                TextColumn::make('created_at')
                    ->dateTime('M d, Y H:i')
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                SelectFilter::make('status')
                    ->label('Status')
                    ->options(
                        collect(PayrollStatus::cases())
                            ->mapWithKeys(fn ($s) => [$s->value => $s->getLabel()])
                    ),

                SelectFilter::make('pay_period_type')
                    ->label('Pay Period')
                    ->options(
                        collect(PayPeriodType::cases())
                            ->mapWithKeys(fn ($p) => [$p->value => $p->getLabel()])
                    ),
            ])
            ->recordActions([
                ViewAction::make(),
                EditAction::make()
                    ->hidden(fn ($record) => $record->status !== PayrollStatus::Draft),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ])
            ->defaultSort('created_at', 'desc');
    }
}
