<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Gas & Maintenance Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1e40af;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #1e40af;
            margin: 0;
            font-size: 20px;
        }
        .header p {
            margin: 4px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 5px 7px;
            text-align: left;
            word-break: break-word;
        }
        th {
            background-color: #1e40af;
            color: #fff;
        }
        .text-right {
            text-align: right;
        }
        .total-row td {
            font-weight: bold;
            background-color: #f7f7f7;
        }
        .footer-note {
            margin-top: 15px;
            font-size: 9px;
            color: #999;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Gas & Maintenance Report</h1>
        <p>
            @if($dateFrom || $dateTo)
                Period: {{ $dateFrom ?: 'earliest' }} to {{ $dateTo ?: 'latest' }}
            @else
                All activity
            @endif
        </p>
        <p>Generated: {{ $generatedAt }}</p>
    </div>

    @if(empty($rows))
        <p style="text-align:center; color:#999; margin-top: 20px;">No gas or maintenance activity found for those filters.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th>Vehicle</th>
                    <th class="text-right">Fuel Cost</th>
                    <th class="text-right">Fuel Liters</th>
                    <th class="text-right">Maintenance Cost</th>
                    <th class="text-right">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($rows as $vehicle)
                    <tr>
                        <td>{{ $vehicle->plate_number }} — {{ $vehicle->full_name }}</td>
                        <td class="text-right">{{ number_format($vehicle->fuel_total, 2) }}</td>
                        <td class="text-right">{{ number_format($vehicle->fuel_liters, 2) }} L</td>
                        <td class="text-right">{{ number_format($vehicle->maintenance_total, 2) }}</td>
                        <td class="text-right">{{ number_format($vehicle->grand_total, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td>Grand Total</td>
                    <td class="text-right">{{ number_format($totals['fuel_total'], 2) }}</td>
                    <td class="text-right">{{ number_format($totals['fuel_liters'], 2) }} L</td>
                    <td class="text-right">{{ number_format($totals['maintenance_total'], 2) }}</td>
                    <td class="text-right">{{ number_format($totals['grand_total'], 2) }}</td>
                </tr>
            </tfoot>
        </table>
    @endif

    <p class="footer-note">Gas & Maintenance Report — generated by TOS Reports.</p>
</body>
</html>
