<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Gas Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1e40af;
            padding-bottom: 15px;
        }
        .header img {
            max-height: 50px;
            margin-bottom: 8px;
        }
        .header h1 {
            color: #1e40af;
            margin: 0;
            font-size: 20px;
        }
        .header p {
            margin: 4px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 5px 7px;
            text-align: left;
            word-break: break-word;
        }
        th {
            background-color: #1e40af;
            color: #fff;
        }
        .text-right {
            text-align: right;
        }
        .total-row td {
            font-weight: bold;
            background-color: #f7f7f7;
        }
        .footer-note {
            margin-top: 15px;
            font-size: 9px;
            color: #999;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        @if($logoDataUri ?? null)
            <img src="{{ $logoDataUri }}" alt="Company Logo">
        @endif
        <h1>Gas Report</h1>
        <p>
            @if($dateFrom || $dateTo)
                Period: {{ $dateFrom ?: 'earliest' }} to {{ $dateTo ?: 'latest' }}
            @else
                All activity
            @endif
        </p>
        <p>Generated: {{ $generatedAt }}</p>
    </div>

    @if(empty($rows))
        <p style="text-align:center; color:#999; margin-top: 20px;">No gas activity found for those filters.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Truck/Unit</th>
                    <th>SI /DR #</th>
                    <th>Gas Station</th>
                    <th class="text-right">Ltrs</th>
                    <th class="text-right">Unit</th>
                    <th class="text-right">Amount</th>
                    <th class="text-right">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($rows as $r)
                    <tr>
                        <td>{{ $r['date'] }}</td>
                        <td>{{ $r['truck'] }}@if($r['plate_number'])<br><span style="color:#888;">{{ $r['plate_number'] }}</span>@endif</td>
                        <td>{{ $r['si_dr_number'] }}</td>
                        <td>{{ $r['fuel_station'] }}</td>
                        <td class="text-right">{{ number_format($r['liters'], 2) }}</td>
                        <td class="text-right">{{ number_format($r['unit_price'], 2) }}</td>
                        <td class="text-right">{{ number_format($r['amount'], 2) }}</td>
                        <td class="text-right">{{ number_format($r['running_total'], 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td colspan="4">Grand Total</td>
                    <td class="text-right">{{ number_format($totals['liters'], 2) }}</td>
                    <td></td>
                    <td class="text-right">{{ number_format($totals['amount'], 2) }}</td>
                    <td class="text-right">{{ number_format($totals['amount'], 2) }}</td>
                </tr>
            </tfoot>
        </table>
    @endif

    <p class="footer-note">Gas Report — generated by TOS Reports.</p>
</body>
</html>
