<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Office Supplies & Bills Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1e40af;
            padding-bottom: 15px;
        }
        .header img {
            max-height: 50px;
            margin-bottom: 8px;
        }
        .header .company-name {
            font-size: 14px;
            font-weight: bold;
            color: #1e40af;
            margin: 0 0 6px;
        }
        .header h1 {
            color: #1e40af;
            margin: 0;
            font-size: 20px;
        }
        .header p {
            margin: 4px 0;
            color: #666;
        }
        .summary {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .summary td {
            border: 1px solid #ddd;
            padding: 5px 7px;
        }
        .summary td:last-child {
            text-align: right;
            font-weight: bold;
        }
        table.ledger {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 5px 7px;
            text-align: left;
            word-break: break-word;
        }
        th {
            background-color: #1e40af;
            color: #fff;
        }
        .text-right {
            text-align: right;
        }
        .total-row td {
            font-weight: bold;
            background-color: #f7f7f7;
        }
        .footer-note {
            margin-top: 15px;
            font-size: 9px;
            color: #999;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        @if($logoDataUri ?? null)
            <img src="{{ $logoDataUri }}" alt="Company Logo">
        @endif
        <p class="company-name">Tri-e Enterprises OPC</p>
        <h1>Office Supplies & Bills Report</h1>
        <p>
            @if($dateFrom || $dateTo)
                Period: {{ $dateFrom ?: 'earliest' }} to {{ $dateTo ?: 'latest' }}
            @else
                All activity
            @endif
        </p>
        <p>Generated: {{ $generatedAt }}</p>
    </div>

    @if(empty($rows))
        <p style="text-align:center; color:#999; margin-top: 20px;">No office supply or bill expenses found for those filters.</p>
    @else
        @if(!empty($byCategory))
            <table class="summary">
                @foreach($byCategory as $category => $amount)
                    <tr>
                        <td>{{ $category }}</td>
                        <td>{{ number_format($amount, 2) }}</td>
                    </tr>
                @endforeach
            </table>
        @endif

        <table class="ledger">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Payee</th>
                    <th>Reference #</th>
                    <th>Description</th>
                    <th class="text-right">Amount</th>
                    <th class="text-right">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($rows as $r)
                    <tr>
                        <td>{{ $r['date'] }}</td>
                        <td>{{ $r['category'] }}</td>
                        <td>{{ $r['payee'] }}</td>
                        <td>{{ $r['reference_number'] }}</td>
                        <td>{{ $r['description'] }}</td>
                        <td class="text-right">{{ number_format($r['amount'], 2) }}</td>
                        <td class="text-right">{{ number_format($r['running_total'], 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td colspan="5">Grand Total</td>
                    <td class="text-right">{{ number_format($totals['amount'], 2) }}</td>
                    <td class="text-right">{{ number_format($totals['amount'], 2) }}</td>
                </tr>
            </tfoot>
        </table>
    @endif

    <p class="footer-note">Office Supplies & Bills Report — generated by TOS Reports.</p>
</body>
</html>
