<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payroll {{ $payroll->payroll_number }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 9px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 2px solid #1e40af;
            padding-bottom: 15px;
        }
        .header img {
            max-height: 50px;
            margin-bottom: 8px;
        }
        .header h1 {
            color: #1e40af;
            margin: 0 0 5px 0;
            font-size: 20px;
        }
        .header p {
            margin: 3px 0;
            color: #666;
            font-size: 10px;
        }
        .meta {
            display: table;
            width: 100%;
            margin-bottom: 15px;
            font-size: 10px;
        }
        .meta-col {
            display: table-cell;
            width: 25%;
        }
        .meta-col .label {
            color: #6b7280;
            font-size: 9px;
        }
        .meta-col .value {
            font-weight: bold;
            color: #111827;
        }
        .status-badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 9px;
            font-weight: bold;
            color: white;
        }
        .status-draft { background-color: #6b7280; }
        .status-approved { background-color: #059669; }
        .status-paid { background-color: #2563eb; }
        .status-cancelled { background-color: #dc2626; }

        .summary-box {
            background-color: #eff6ff;
            border: 1px solid #bfdbfe;
            border-radius: 8px;
            padding: 12px;
            margin-bottom: 15px;
        }
        .summary-grid {
            display: table;
            width: 100%;
        }
        .summary-item {
            display: table-cell;
            width: 33.33%;
            text-align: center;
        }
        .summary-item .label {
            font-size: 9px;
            color: #6b7280;
            margin-bottom: 3px;
        }
        .summary-item .value {
            font-size: 15px;
            font-weight: bold;
            color: #111827;
        }
        .summary-item .value.net {
            color: #059669;
        }
        .summary-item .value.deductions {
            color: #dc2626;
        }

        table.items {
            width: 100%;
            border-collapse: collapse;
        }
        table.items th, table.items td {
            padding: 5px 6px;
            border-bottom: 1px solid #e5e7eb;
            text-align: left;
        }
        table.items th {
            background-color: #f3f4f6;
            font-weight: bold;
            color: #374151;
            font-size: 8px;
            text-transform: uppercase;
        }
        table.items td.amount, table.items th.amount {
            text-align: right;
            font-family: 'DejaVu Sans Mono', monospace;
        }
        table.items tr:nth-child(even) {
            background-color: #fafafa;
        }
        table.items tfoot td {
            border-top: 2px solid #374151;
            border-bottom: none;
            font-weight: bold;
            background-color: #f9fafb;
        }
        .net-pay {
            color: #059669;
            font-weight: bold;
        }
        .deduction {
            color: #dc2626;
        }

        .footer {
            margin-top: 20px;
            padding-top: 15px;
            border-top: 1px solid #e5e7eb;
            font-size: 9px;
            color: #6b7280;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        @if ($logoDataUri)
            <img src="{{ $logoDataUri }}" alt="Company Logo">
        @endif
        <h1>Tri-E Enterprises</h1>
        <p>Payroll Statement &mdash; {{ $payroll->payroll_number }} &middot; {{ $payroll->pay_period_type->getLabel() }}</p>
        <p>Pay Period: {{ $payroll->pay_period_start->format('F d, Y') }} &ndash; {{ $payroll->pay_period_end->format('F d, Y') }}</p>
    </div>

    <div class="meta">
        <div class="meta-col">
            <div class="label">Status</div>
            <div class="value">
                <span class="status-badge status-{{ $payroll->status->value }}">{{ $payroll->status->getLabel() }}</span>
            </div>
        </div>
        <div class="meta-col">
            <div class="label">Generated By</div>
            <div class="value">{{ $payroll->generatedBy?->name ?? '-' }}</div>
        </div>
        <div class="meta-col">
            <div class="label">Approved By</div>
            <div class="value">{{ $payroll->approvedBy?->name ?? '-' }}</div>
        </div>
        <div class="meta-col">
            <div class="label">Generated</div>
            <div class="value">{{ $generatedAt }}</div>
        </div>
    </div>

    <div class="summary-box">
        <div class="summary-grid">
            <div class="summary-item">
                <div class="label">Total Gross</div>
                <div class="value">₱{{ number_format((float) $payroll->total_gross, 2) }}</div>
            </div>
            <div class="summary-item">
                <div class="label">Total Deductions</div>
                <div class="value deductions">₱{{ number_format((float) $payroll->total_deductions, 2) }}</div>
            </div>
            <div class="summary-item">
                <div class="label">Total Net Pay</div>
                <div class="value net">₱{{ number_format((float) $payroll->total_net, 2) }}</div>
            </div>
        </div>
    </div>

    <table class="items">
        <thead>
            <tr>
                <th>Employee</th>
                <th class="amount">Daily Rate</th>
                <th class="amount">Days Worked</th>
                <th class="amount">Absent</th>
                <th class="amount">OT Hrs</th>
                <th class="amount">OT Pay</th>
                <th class="amount">Bonus</th>
                <th class="amount">Allowance</th>
                <th class="amount">Gross</th>
                <th class="amount">Late</th>
                <th class="amount">SSS</th>
                <th class="amount">PhilHealth</th>
                <th class="amount">Pag-IBIG</th>
                <th class="amount">Other</th>
                <th class="amount">Total Ded.</th>
                <th class="amount">Net Pay</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($payroll->payrollItems as $item)
                <tr>
                    <td>{{ $item->employee?->name ?? '-' }}</td>
                    <td class="amount">₱{{ number_format((float) $item->daily_rate, 2) }}</td>
                    <td class="amount">{{ number_format((float) $item->days_worked, 2) }}</td>
                    <td class="amount">{{ number_format((float) $item->days_absent, 2) }}</td>
                    <td class="amount">{{ number_format((float) $item->overtime_hours, 2) }}</td>
                    <td class="amount">₱{{ number_format((float) $item->overtime_pay, 2) }}</td>
                    <td class="amount">₱{{ number_format((float) $item->bonus, 2) }}</td>
                    <td class="amount">₱{{ number_format((float) $item->allowance, 2) }}</td>
                    <td class="amount">₱{{ number_format((float) $item->gross_pay, 2) }}</td>
                    <td class="amount deduction">₱{{ number_format((float) $item->late_deduction, 2) }}</td>
                    <td class="amount deduction">₱{{ number_format((float) $item->sss_deduction, 2) }}</td>
                    <td class="amount deduction">₱{{ number_format((float) $item->philhealth_deduction, 2) }}</td>
                    <td class="amount deduction">₱{{ number_format((float) $item->pagibig_deduction, 2) }}</td>
                    <td class="amount deduction">₱{{ number_format((float) $item->other_deduction, 2) }}</td>
                    <td class="amount deduction">₱{{ number_format((float) $item->total_deductions, 2) }}</td>
                    <td class="amount net-pay">₱{{ number_format((float) $item->net_pay, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="8">TOTAL</td>
                <td class="amount">₱{{ number_format((float) $payroll->total_gross, 2) }}</td>
                <td colspan="5"></td>
                <td class="amount">₱{{ number_format((float) $payroll->total_deductions, 2) }}</td>
                <td class="amount net-pay">₱{{ number_format((float) $payroll->total_net, 2) }}</td>
            </tr>
        </tfoot>
    </table>

    @if ($payroll->notes)
        <div class="footer" style="text-align: left; border-top: none; margin-top: 10px; padding-top: 0;">
            <strong>Notes:</strong> {{ $payroll->notes }}
        </div>
    @endif

    <div class="footer">
        <p>This payroll statement was automatically generated. Please verify all figures before disbursement.</p>
    </div>
</body>
</html>
