<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Statement of Account - {{ $supplier->name }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1e40af;
            padding-bottom: 15px;
        }
        .header img {
            max-height: 50px;
            margin-bottom: 8px;
        }
        .header h1 {
            color: #1e40af;
            margin: 0;
            font-size: 20px;
        }
        .header p {
            margin: 4px 0;
            color: #666;
        }
        .month-title {
            background-color: #eef2ff;
            color: #1e40af;
            font-size: 12px;
            font-weight: bold;
            padding: 6px 8px;
            margin-top: 18px;
        }
        .balance-row td {
            font-weight: bold;
            background-color: #f7f7f7;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 5px 7px;
            text-align: left;
            word-break: break-word;
        }
        th {
            background-color: #1e40af;
            color: #fff;
        }
        .text-right {
            text-align: right;
        }
        .footer-note {
            margin-top: 15px;
            font-size: 9px;
            color: #999;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        @if($logoDataUri ?? null)
            <img src="{{ $logoDataUri }}" alt="Company Logo">
        @endif
        <h1>Statement of Account</h1>
        <p>{{ $supplier->name }}</p>
        <p>
            @if($dateFrom || $dateTo)
                Period: {{ $dateFrom ?: 'earliest' }} to {{ $dateTo ?: 'latest' }}
            @else
                All activity
            @endif
        </p>
        <p>Generated: {{ $generatedAt }}</p>
    </div>

    @forelse($months as $month)
        <div class="month-title">{{ $month['label'] }}</div>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>SI #</th>
                    <th>P.O #</th>
                    <th class="text-right">Total</th>
                    <th class="text-right">Total Amount</th>
                </tr>
            </thead>
            <tbody>
                @php $runningTotal = 0; @endphp
                @foreach($month['purchases'] as $purchase)
                    @php $runningTotal += (float) $purchase->total; @endphp
                    <tr>
                        <td>{{ $purchase->date->format('j-M-y') }}</td>
                        <td>{{ $purchase->si_number ?: '—' }}</td>
                        <td>{{ $purchase->po_number ?: '—' }}</td>
                        <td class="text-right">{{ number_format($purchase->total, 2) }}</td>
                        <td class="text-right">{{ number_format($runningTotal, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @empty
        <p style="text-align:center; color:#999; margin-top: 20px;">No purchase activity for this supplier in the selected period.</p>
    @endforelse

    <p class="footer-note">Statement of Account — generated by the Custom Report Builder.</p>
</body>
</html>
